replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: sashash986/minikube
  tag: frontend
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: frontend
  type: NodePort
  servicePort: 3000 # the port where nginx serves its traffic
