replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: sashash986/minikube
  tag: backend
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: backend
  type: NodePort
  servicePort: 5000
services:
  mongo:
     url: mongo-mongodb
     name: todos
     env: production
